import 'package:custom_clothes/common/model/enum/catetory_label.dart';
import 'package:custom_clothes/common/model/product_model.dart';

List<ProductModel> totalProductItems = [
  ProductModel(
    id: '15',
    isCompletion: false,
    assetImageName: 'asset/image/product/15.png',
    fileImage: null,
    productName: '블랑 트위드 자켓',
    productPrice: 58000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.outer,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '16',
    isCompletion: false,
    assetImageName: 'asset/image/product/16.png',
    fileImage: null,
    productName: '기본 싱글 카라 린넨 랑방 싱글 자켓',
    productPrice: 66000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.outer,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '13',
    isCompletion: false,
    assetImageName: 'asset/image/product/13.png',
    fileImage: null,
    productName: '도빌 린넨 자켓',
    productPrice: 46000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.outer,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '14',
    isCompletion: false,
    assetImageName: 'asset/image/product/14.png',
    fileImage: null,
    productName: '레브 카라 트위드 자켓',
    productPrice: 43000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.outer,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '8',
    isCompletion: false,
    assetImageName: 'asset/image/product/8.png',
    fileImage: null,
    productName: '린넨 쇼츠',
    productPrice: 21000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.bottom,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '9',
    isCompletion: false,
    assetImageName: 'asset/image/product/9.png',
    fileImage: null,
    productName: 'A라인 볼륨 데님 반바지',
    productPrice: 24000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.bottom,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '10',
    isCompletion: false,
    assetImageName: 'asset/image/product/10.png',
    fileImage: null,
    productName: '체크 풀 sk',
    productPrice: 21000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.bottom,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '5',
    isCompletion: false,
    assetImageName: 'asset/image/product/5.png',
    fileImage: null,
    productName: '모먼트 원피스',
    productPrice: 30000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.onePiece,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '6',
    isCompletion: false,
    assetImageName: 'asset/image/product/6.png',
    fileImage: null,
    productName: '수채화 나염 원피스',
    productPrice: 28000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.onePiece,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '7',
    isCompletion: false,
    assetImageName: 'asset/image/product/7.png',
    fileImage: null,
    productName: '스트라이프 라운드 넥 크로스 원피스',
    productPrice: 30000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.onePiece,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '11',
    isCompletion: false,
    assetImageName: 'asset/image/product/11.png',
    fileImage: null,
    productName: '모니카 와샤 셔츠',
    productPrice: 21000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.top,
    ],
    fabrics: {},
  ),
  ProductModel(
    id: '12',
    isCompletion: false,
    assetImageName: 'asset/image/product/12.png',
    fileImage: null,
    productName: '비바 실키 셔츠',
    productPrice: 19000,
    customPrice: 17000,
    categories: [
      CategoryLabel.recommend,
      CategoryLabel.top,
    ],
    fabrics: {},
  ),
];

List<ProductModel> userProductItems = [];
